### ISSUE TITLE
build error: html files should be copied from their location instead of assuming they are in outDir

### ISSUE THREAD

**Issue by zoranpopovic** [WindsonFF/vite-plugin-virtual-html#3] opened 2021-06-12 17:33 UTC
I get the following error: `[vite-plugin-virtual-html] ENOENT: no such file or directory, copyfile 'C:\Users\zoran\src\enlearn\math\Projects\Activities\wwwroot\vite-pages\Activity.html' -> 'C:\Users\zoran\src\enlearn\math\Projects\Activities\wwwroot\Activity.html'`
 with vite build

to clarify base: '/'  outDir: "Projects/Activities/wwwroot" and pages have the structure `Login: '/vite-pages/Login.html',` meaning that vite-pages directory is in the base directory.

The plugin seems to assume that pages are also in the outDir.  My guess is that it should resolve the source path from the `base` directory not outDir.  But i'm not sure.  In any case, it should resolve the source pages the same way as vite dev does.

**Comment by WindsonFF** [comment] 2021-06-13 03:37
maybe fixed in `0.0.9`. can you try update it?

**Comment by zoranpopovic** [comment] 2021-06-13 13:24
I was running it on 0.9.  i think the issue is with this line https://github.com/WindsonFF/vite-plugin-virtual-html/blob/70c277e569b21fc69f8af268a3169be117b2870b/src/index.ts#L67

because that's not the location of the file.

**Comment by WindsonFF** [comment] 2021-06-13 16:53
i didn't reproduce this.
can u provide a little demo to test ?

**Comment by zoranpopovic** [comment] 2021-06-14 16:49
yes, if outDir starts with a slash the copy error occurs, but not if path is relative (without slash).

**Comment by WindsonFF** [comment] 2021-06-15 01:53
so ,you change your config and it's worked?

**Comment by zoranpopovic** [comment] 2021-06-18 03:15
still can't figure out the exact reason why it failed.  why was it failing for you on windows with  outDir: '/Projects/wwwRoot/www'

**Comment by imguolao** [comment] 2021-07-02 03:44
I got the same error on win7 and win10 when using `vite build`，but it doesn't happen every time.

I think the reason is in this line of code.

https://github.com/WindsonFF/vite-plugin-virtual-html/blob/70c277e569b21fc69f8af268a3169be117b2870b/src/index.ts#L67

**Comment by WindsonFF** [comment] 2021-07-02 05:18
> I got the same error on win7 and win10 when using `vite build`，but it doesn't happen every time.
> 
> I think the reason is in this line of code.
> 
> https://github.com/WindsonFF/vite-plugin-virtual-html/blob/70c277e569b21fc69f8af268a3169be117b2870b/src/index.ts#L67
> 

😂😂😂😂 i can't reproduce it....

**Comment by WindsonFF** [comment] 2021-07-03 05:00
i've remove this `./` from code and published `0.0.10`. i maybe resolve this issue. pls try it.

**Comment by imguolao** [comment] 2021-07-06 12:41
```sh
$ yarn run build
yarn run v1.22.10
$ vite build
vite v2.3.7 building for production...
✓ 12 modules transformed.
[vite-plugin-virtual-html] ENOENT: no such file or directory, copyfile 'D:\publicGroup\rasfire\dist\vite\build\index.html' -> 'D:\publicGroup\rasfire\dist\index.html'
error during build:
Error: ENOENT: no such file or directory, copyfile 'D:\publicGroup\rasfire\dist\vite\build\index.html' -> 'D:\publicGroup\rasfire\dist\index.html'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`0.0.10` not working, the error still exist.

**Comment by imguolao** [comment] 2021-07-06 12:50
https://github.com/WindsonFF/vite-plugin-virtual-html/blob/70c277e569b21fc69f8af268a3169be117b2870b/src/index.ts#L62

It is strange that the `closeBundle` hook runs directly after the 'vite build' has been executed, rather than last.

![closebundle](https://user-images.githubusercontent.com/25502024/124602699-b4d3ab00-de9b-11eb-994b-a37ce9102879.PNG)

**Comment by WindsonFF** [comment] 2021-07-07 01:49
😂😂😂😂😂

**Comment by imguolao** [comment] 2021-07-09 08:33
I think I have found the cause of the error.

If throw any error in hook of rollup server, the server would be closes and executes the `closeBundle` hook. And then, the error of  the fsp.copyFile function is thrown by Node, interrupting the vite execution and not thrown subsequent errors.

![vite_plugin_api](https://user-images.githubusercontent.com/25502024/125048599-ad4a1700-e0d2-11eb-92e6-7d86b16f3a65.PNG)

So, I added a few lines of code to check if the file exists.

https://github.com/WindsonFF/vite-plugin-virtual-html/blob/70c277e569b21fc69f8af268a3169be117b2870b/src/index.ts#L62

```js
async closeBundle() {
    const pageKeys = Object.keys(pages);
    const pathToRemove = [];
    for (const pageKey of pageKeys) {
        // original build html path
        const src = path.resolve(process.cwd(), `./${outDir}/${pages[pageKey]}`);
        const pageArr = pages[pageKey].split('/');
        const pageName = pageArr[pageArr.length - 1];
        // dest html path
        const dest = path.resolve(process.cwd(), `./${outDir}/${pageName}`);

        // check
        try {
            await fsp.access(src);
            await fsp.copyFile(src, dest);
            pathToRemove.push(pageArr[1]);
        } catch {
            console.error('')
        }
    }
    // remove extra folder
    for (const toRemove of pathToRemove) {
        // catch rmdir's exception.
        // rmdir maybe remove a dir already remove.
        try {
            await fsp.rmdir(path.resolve(process.cwd(), `./${outDir}/${toRemove}`), { recursive: true });
        } catch (e) {}
    }
}
```

**Comment by WindsonFF** [comment] 2021-07-09 14:16
please submit a PR. I'll merge it.

**Comment by zoranpopovic** [comment] 2021-08-20 05:19
did the latest changes to main that check for file before file operations get released?  I'm curious whether the issue is fixed with them.

**Closed** 2021-08-20 05:34 UTC
